[package]
authors = ["L-oris <loris4526@gmail.com>"]
edition = "2018"
name = "sort_md_translations"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
